networks:
  project_network:
    external: true
    driver: bridge
services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/app
      - /app/node_modules
    restart: always
    ports: 
      - '3050:8080'
    depends_on:
      - dockerbackend
      - dockerfrontend
    networks:
      - project_network
  dockerbackend:
    build: 
      context: ./RailsApplication
      dockerfile: Dockerfile
    container_name: backenddocker
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - ./RailsApplication:/app
      - /app/node_modules
    ports:
      -  3001:3000
    networks:
      - project_network
    tty: true
    stdin_open: true
    depends_on:
      - db
  dockerfrontend:
    build: 
      context: ./capblog
      dockerfile: Dockerfile
    container_name: frontenddocker
    volumes:
      - ./capblog:/app
      - /app/node_modules
    networks:
      - project_network
    ports:
      - 3005:3005
    environment: 
      CHOKIDAR_USEPOLLING: "true"    
    links:
      - dockerbackend
    tty: true
    stdin_open: true

